name: Build docker image

on:
  push:
    branches: '*'

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/bagaco-ramp-up/python-101/docker_fun:latest docker_fun/
        echo $TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/bagaco-ramp-up/python-101/docker_fun:latest
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}