name: Github comment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"   
    - name: Install dependencies
      run: |
        pip3 install requests
    - name: make a comment
      env:
        PR_NUMBER: ${{ github.event.number }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 github_comment_on_pr/comment_on_pr.py $PR_NUMBER "hello world" $TOKEN
